sudo: required 
services: 
    - docker

before_install:
    - docker build -t johnalejandro001/react-web -f Dockerfile.dev .

script:
    - docker run johnalejandro001/react-web npm run test -- --coverage
