sudo: required
services:
- docker
- openssl aes-256-cbc -K $encrypted_78b7adbb5290_key -iv $encrypted_78b7adbb5290_iv
  -in client-secret.json.enc -out client-secret.json -d
before_install:
- docker build -t johnalejandro001/react-web -f Dockerfile.dev .
script:
- docker run -e CI=true johnalejandro001/react-web npm run test -- --coverage
deploy:
  provider: gae
  keyfile: client-secret.json.enc
  project: mineral-silicon-264703


