sudo: required
services:
- docker
before_install:
openssl aes-256-cbc -K $encrypted_78b7adbb5290_key -iv $encrypted_78b7adbb5290_iv -in client-secret.json.enc -out client-secret.json -d
- docker build -t johnalejandro001/react-web -f Dockerfile.dev .
script:
- docker run -e CI=true johnalejandro001/react-web npm run test -- --coverage
deploy:
  provider: gae
  keyfile: client-secret.json
  project: mineral-silicon-264703
  on:
     branch: master
env:
  global:
    secure: tmaeqQShv8ShEbwIDrySljfFvw4QZ3QwgFDNkyfbTCWY0W3rI/u39a1HhyUGbT6iY6H9fBmGOe7lOOAAhTfQxSmkFDePScnAU1wTkqX/+w1oTHxKFGW8ftmV+iYOpy7LoKaLOpln8vXg/Nih1VqOLuRvn203kKGrN5rscHKG+rPl1U68nI/oa0huIK6JaDFBQwcK64EBsXommwpkTPmfBAbnJ0R8kGmSYS1jmELbtmA+6LeeVbIoOR4xGxwG91KZjU4pw83kTvzaqH4mSLExJWfQnf3WOKMLeJ6J91Pq5qFxuSxdL7hoUKe/7PAgSN2yIIklIENKGHKTwlu67D2ztliYeZLBH5KU5KwINrwy90rV+06XqUykYg+KCvUzriN92Nx6LRg6M3c4tulVJo3rIejjVRJQCWO4rUUbM6t11x2NpYgMO9RcMrlmZuBpffjn+7/q9dAQCOHWNR1s8Ln6sjaHZ3lWdxgJ2iM51Z8sd7Pbvl4vISqLAW+Gk+eLaNRxpawZjZMl4k9yt0n/XicPb1Dt/jWZAWwCaGLTMKVpXA8BHeNDoPczGQou7Nsjc5u6sQDpZDdKbIe0EyQ3Qvd25How18j0HLXLwXKDrQorbkv3qruxR1nWuxE9g7ewkzkrssaCsZWC8UbseXD1U483M2nZKXWyxfwrHH3DeQTULlE=
